version: "3.0"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5443:5432"
    environment:
      POSTGRES_DB: parkeerrecht
      POSTGRES_USER: parkeerrecht
      POSTGRES_PASSWORD: insecure

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/parkeerrechten:${ENVIRONMENT}
    links:
      - database
    environment:
      PARKEREN_OBJECTSTORE_PASSWORD: ${PARKEREN_OBJECTSTORE_PASSWORD}
      DATABASE_NAME: parkeerrecht
      DATABASE_USER: parkeerrecht
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
    command: make runimport

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database
    environment:
      PARKEREN_OBJECTSTORE_PASSWORD: ${PARKEREN_OBJECTSTORE_PASSWORD}
      DATABASE_NAME: parkeerrecht
      DATABASE_USER: parkeerrecht
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database:db
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo db:5432:parkeerrecht:parkeerrecht:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump  -Fc \
                          -U parkeerrecht \
                          -h db -p 5432 \
                          parkeerr > /tmp/backups/database.dump"
