version: "3.0"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5443:5432"
    environment:
      POSTGRES_DB: parkeerrechten
      POSTGRES_USER: parkeerrechten
      POSTGRES_PASSWORD: insecure

  app:
    build: ./parkeerrechten
    links:
      - database
    environment:
      PARKEREN_OBJECTSTORE_PASSWORD: ${PARKEREN_OBJECTSTORE_PASSWORD}
      DATABASE_NAME: parkeerrechten
      DATABASE_USER: parkeerrechten
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
